import {Container, CssBaseline} from '@mui/material';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import authenticated from './auth/actions/authenticated';
import './globals.css';
import Header from './header/header';
import Provider from './provider';
import logout from './auth/logout';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />
          <Container className={isAuthenticated ? 'm-10' : ''}>
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
